import Anthropic from '@anthropic-ai/sdk';
import { HttpsProxyAgent } from 'https-proxy-agent';
import { createClient } from '@supabase/supabase-js';

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
  // Only use proxy in local development (when NODE_ENV is not production)
  ...(process.env.NODE_ENV !== 'production' && {
    httpAgent: new HttpsProxyAgent('http://127.0.0.1:10809'),
  }),
});

// Initialize Supabase client (server-side)
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
);

// ═══════════════════════════════════════════════════════════
// PRODUCTION-GRADE PROMPTS (from VibeCheck Manual v1.0)
// ═══════════════════════════════════════════════════════════

const SYSTEM_PROMPT = `# VibeCheck — AI Code Security Analyst v1.0

## Role
You are VibeCheck's core analysis engine, specializing in detecting security vulnerabilities,
technical debt, and maintainability issues in code generated by AI-assisted programming tools
(Cursor, GitHub Copilot, Claude Code).

## Professional Boundaries — Focus on AI-Generated Code Failure Patterns
- Hardcoded credentials (API keys, passwords, tokens, private keys)
- Injection vulnerabilities (SQL injection, XSS, command injection, SSRF)
- Unsafe deserialization and input handling
- Over-authorization and missing authentication checks
- Async code without error handling (uncaught Promise rejections)
- Repetitive logic and high coupling (DRY violations)
- Untestable functions (overly long, excessive side effects, unmockable dependencies)

## Output Conventions
- Always respond with valid JSON, no preamble, explanation, or markdown code blocks
- All plain_english fields use simple, direct language assuming readers don't know security terminology
- Fix suggestions must include copy-pasteable code examples (not pseudocode)
- Use estimated line descriptions: "around line X" or "inside functionName function"
- Language: Strictly follow the language specified in the output_format (English or Chinese)

## Uncertainty Rules (Anti-Hallucination)
- Unconfirmed issues: set confidence to "low", add "[Unconfirmed]" to title
- Incomplete code snippets: explain missing context in meta.incomplete
- Only reference content actually present in <code> tags, don't infer framework behavior
- If input is not code: set score to 0, empty issues array, explain in meta`;

const createScanPrompt = (code, language = 'auto', outputLang = 'en') => {
  const instructions = outputLang === 'zh'
    ? '分析以下代码片段。严格按照 output_format 中的 JSON Schema 返回结果。不要在 JSON 之外输出任何内容，不要包裹 markdown 代码块。'
    : 'Analyze the following code snippet. Strictly follow the JSON Schema in output_format. Do not output anything outside of JSON, do not wrap with markdown code blocks.';

  const outputFormat = outputLang === 'zh' ? `{
  "score": 0-100,        // 综合健康分。100=完美，<60=需立即处理
  "grade": "A|B|C|D|F",  // A≥90, B≥75, C≥60, D≥45, F<45

  "summary": {
    "headline": "最紧迫的一件事，15字以内，直接说",
    "detail": "2句整体评价，开门见山"
  },

  "issues": [
    {
      "id": "ISSUE-001",
      "severity": "critical|high|medium|low",
      "category": "security|maintainability|performance|bug_risk",
      "title": "问题标题，10字以内",
      "plain_english": "一句人话说清楚危害是什么，假设读者不懂安全",
      "location": "大约在哪里，如：'第15行的数据库连接' 或 'getUser函数内'",
      "confidence": "high|medium|low",
      "fix": {
        "description": "一句话说怎么改",
        "code": "可直接粘贴的修复代码，不能是伪代码。无合适代码则为 null"
      }
    }
  ],

  "positives": [
    "代码做得好的地方，1-3条，只写真实存在的优点，不要捏造"
  ],

  "meta": {
    "language_detected": "检测到的编程语言",
    "lines_analyzed": 0,
    "incomplete": "null 或说明缺失的上下文（如：'缺少数据库连接的定义'）",
    "ai_generated_confidence": "high|medium|low|unknown"
  }
}` : `{
  "score": 0-100,        // Overall health score. 100=perfect, <60=urgent fixes needed
  "grade": "A|B|C|D|F",  // A≥90, B≥75, C≥60, D≥45, F<45

  "summary": {
    "headline": "The most urgent issue in 15 words or less",
    "detail": "2-sentence overall assessment, be direct"
  },

  "issues": [
    {
      "id": "ISSUE-001",
      "severity": "critical|high|medium|low",
      "category": "security|maintainability|performance|bug_risk",
      "title": "Issue title, 10 words max",
      "plain_english": "Explain the risk in simple terms, assume reader doesn't know security",
      "location": "Approximate location, e.g., 'line 15 database connection' or 'inside getUser function'",
      "confidence": "high|medium|low",
      "fix": {
        "description": "One-sentence fix description",
        "code": "Copy-pasteable fix code (not pseudocode). Use null if no suitable code example"
      }
    }
  ],

  "positives": [
    "Things the code does well, 1-3 items, only mention real strengths"
  ],

  "meta": {
    "language_detected": "Detected programming language",
    "lines_analyzed": 0,
    "incomplete": "null or description of missing context (e.g., 'missing database connection definition')",
    "ai_generated_confidence": "high|medium|low|unknown"
  }
}`;

  return `<instructions>
${instructions}
</instructions>

<code language="${language}">
${code}
</code>

<output_format>
${outputFormat}
</output_format>`;
};

// ═══════════════════════════════════════════════════════════
// RATE LIMITING & USER MANAGEMENT
// ═══════════════════════════════════════════════════════════

async function checkRateLimit(userId) {
  const today = new Date().toISOString().split('T')[0];

  // Get or create today's usage record
  const { data: usage, error } = await supabase
    .from('user_usage')
    .select('scan_count')
    .eq('user_id', userId)
    .eq('date', today)
    .single();

  if (error && error.code !== 'PGRST116') {
    // PGRST116 = no rows returned
    throw error;
  }

  const currentCount = usage?.scan_count || 0;

  // Get user's plan
  const { data: profile } = await supabase
    .from('profiles')
    .select('plan')
    .eq('id', userId)
    .single();

  const plan = profile?.plan || 'free';
  const limit = plan === 'free' ? 3 : 999; // Free: 3/day, Paid: unlimited

  if (currentCount >= limit) {
    return { allowed: false, remaining: 0, limit };
  }

  return { allowed: true, remaining: limit - currentCount - 1, limit };
}

async function incrementUsage(userId) {
  const today = new Date().toISOString().split('T')[0];

  const { error } = await supabase
    .from('user_usage')
    .upsert({
      user_id: userId,
      date: today,
      scan_count: 1,
    }, {
      onConflict: 'user_id,date',
      // Increment scan_count if record exists
    });

  if (error) {
    // If upsert fails, try manual increment
    await supabase.rpc('increment_scan_count', {
      p_user_id: userId,
      p_date: today
    });
  }
}

async function saveScanHistory(userId, code, result) {
  await supabase.from('scan_history').insert({
    user_id: userId,
    language: result.meta?.language_detected || 'unknown',
    score: result.score,
    grade: result.grade,
    issues_count: result.issues?.length || 0,
    result_json: result,
  });
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { code, language = 'auto', outputLang = 'en' } = req.body;

  if (!code || typeof code !== 'string') {
    return res.status(400).json({ error: 'Code is required' });
  }

  if (!process.env.ANTHROPIC_API_KEY) {
    return res.status(500).json({ error: 'API key not configured' });
  }

  // ═══════════════════════════════════════════════════════════
  // AUTHENTICATION & RATE LIMITING
  // ═══════════════════════════════════════════════════════════

  // Get user from Authorization header (if provided)
  const authHeader = req.headers.authorization;
  let userId = null;

  if (authHeader?.startsWith('Bearer ')) {
    const token = authHeader.substring(7);
    const { data: { user }, error } = await supabase.auth.getUser(token);

    if (user) {
      userId = user.id;

      // Check rate limit for authenticated users
      const rateLimit = await checkRateLimit(userId);

      if (!rateLimit.allowed) {
        return res.status(429).json({
          error: 'Daily limit reached',
          message: `You've used all ${rateLimit.limit} free scans today. Upgrade to continue scanning.`,
          limit: rateLimit.limit,
          remaining: 0,
        });
      }
    }
  }

  // For unauthenticated users: allow scan but don't track
  // (Frontend will use localStorage for soft limit)

  try {
    // Prefilling technique: force JSON output by starting assistant message with "{"
    const message = await anthropic.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 4096,
      temperature: 0.2, // Lower temperature for more consistent output
      system: SYSTEM_PROMPT,
      messages: [
        {
          role: 'user',
          content: createScanPrompt(code, language, outputLang),
        },
        {
          role: 'assistant',
          content: '{', // Prefilling - Claude will continue from here, skipping any preamble
        },
      ],
    });

    // Reconstruct the JSON by adding back the opening brace
    const rawJson = '{' + message.content[0].text;

    // Parse the JSON response
    let result;
    try {
      result = JSON.parse(rawJson);
    } catch (parseError) {
      console.error('JSON parse error:', parseError);
      console.error('Raw response:', rawJson);

      // Fallback: try to extract JSON from the response
      const jsonMatch = rawJson.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        result = JSON.parse(jsonMatch[0]);
      } else {
        throw new Error('Failed to parse Claude response as JSON');
      }
    }

    // Validate required fields
    if (
      typeof result.score !== 'number' ||
      !result.grade ||
      !result.summary ||
      !Array.isArray(result.issues) ||
      !result.meta
    ) {
      throw new Error('Invalid response structure from Claude');
    }

    // ═══════════════════════════════════════════════════════════
    // TRACK USAGE & SAVE HISTORY (for authenticated users)
    // ═══════════════════════════════════════════════════════════

    if (userId) {
      try {
        await incrementUsage(userId);
        await saveScanHistory(userId, code, result);
      } catch (dbError) {
        console.error('Database error:', dbError);
        // Continue even if tracking fails
      }
    }

    return res.status(200).json(result);

  } catch (error) {
    console.error('Scan error:', error);

    if (error.status === 401) {
      return res.status(500).json({ error: 'Invalid API key' });
    }

    if (error.status === 429) {
      return res.status(429).json({ error: 'Rate limit exceeded. Please try again later.' });
    }

    return res.status(500).json({
      error: error.message || 'Failed to scan code. Please try again.'
    });
  }
}
